print("INPUT")
nama = input("Nama lengkap\t\t:")
nim = input("NIM\t\t\t:")
kelas = input("Kelas Paralel\t\t:")
tempat = input("Tempat/Tanggal Lahir\t:")
alamat = input("Alamat\t\t\t:")
hobby = input("Hobby\t\t\t:")
hp = input("No.HP\t\t\t:")

print("OUTPUT")
print("Nama Lengkap\t\t:"+ nama)
print("NIM\t\t\t:"+ nim)
print("Kelas Paralel\t\t:"+ kelas)
print("Tempat/Tanggal Lahir\t:"+ tempat)
print("Alamat\t\t\t:"+ alamat)
print("Hobby\t\t\t:"+ hobby)
print("No.HP\t\t\t:"+ hp)