print("INPUT")
a = float(input("Masukan Nilai a\t:"))
b = float(input("Masukan Nilai b\t:"))
i = float(input("Masukan Nilai i\t:"))
j = float(input("Masukan Nilai j\t:"))
x = float(input("Masukan Nilai x\t:"))
y = float(input("Masukan Nilai y\t:"))
hasil = (a - b) * i / j - (x + y)
print("OUTPUT")
print("{:.3f}".format(hasil))